export const dummyTasks = [
  {
    id: "1",
    task: "Task 1",
    description: "Complete the homepage layout.",
    assignee: "Alice",
    start: "2024-10-20",
    end: "2024-10-25",
    priority: "High",
    status: "In Progress",
    project: "Website Redesign",
  },
  {
    id: "2",
    task: "Task 2",
    description: "Implement the sidebar component.",
    assignee: "Bob",
    start: "2024-10-22",
    end: "2024-10-30",
    priority: "Medium",
    status: "Not Started",
    project: "Website Redesign",
  },
  {
    id: "3",
    task: "Task 3",
    description: "Write unit tests for the dashboard.",
    assignee: "Charlie",
    start: "2024-10-23",
    end: "2024-10-28",
    priority: "Low",
    status: "COMPLETED",
    project: "Dashboard Improvements",
  },
  {
    id: "4",
    task: "Task 4",
    description: "Review PRs for the sidebar and dashboard.",
    assignee: "David",
    start: "2024-10-25",
    end: "2024-10-27",
    priority: "High",
    status: "In Progress",
    project: "Website Redesign",
  },
  {
    id: "5",
    task: "Task 5",
    description: "Finalize project documentation.",
    assignee: "Eve",
    start: "2024-10-26",
    end: "2024-11-01",
    priority: "Medium",
    status: "Not Started",
    project: "Documentation",
  },
];

export default dummyTasks;
